### ISSUE TITLE
Request to have access to bats helpers

### ISSUE THREAD

**Issue by paulvitic** [CircleCI-Public/BATS-orb#2]
**Is your feature request related to a problem? Please describe.**
Is there a reason why bats helpers such as bats-support, bats-assert and bats-files are not installed? They are useful for writing clean bats tests.

**Describe the solution you'd like**
Please install bats helpers

**Describe alternatives you've considered**
Installing bats helpers in own orb project under *src/tests/test_helper* folder.

**Comment by KyleTryon** [comment]
Only a year late to taking a look at this 🙏 . Im thinking about it now and wondering what the best way to implement this is. 

https://github.com/ztombol/bats-docs#git-submodule
https://bats-core.readthedocs.io/en/stable/faq.html#how-can-i-use-helper-libraries-like-bats-assert

So your bats tests will need to include something like:

```
setup() {
    load 'test_helper/bats-support/load' # this is required by bats-assert!
    load 'test_helper/bats-assert/load'
}
```
Where the helper function path would likely be set by your code, and not something to be overwritten by the orb. In the first link, the documentation recommends using git submodules to bring the helper files into the repo. Im not a huge fan of submodules but I can see why they suggested this. 

The last suggestion they give is to clone the helper files. We could do this, but im not sure how we'd want to implement this in the orb, we could "bake-in" all of the helpers and allow you to specify where to put them so that it matches your code. But we couldn't then support custom helpers or guarantee version.

My feeling now, is it is probably best to lock the helper version to your code like a package, which is what a git submodule will effectively do.

**Comment by KyleTryon** [comment]
Closing this issue for now. For anyone who may stumble upon this, please open a new issue referencing this one.
